services:
  - type: worker
    name: expense-tracker-bot
    runtime: docker
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: GOOGLE_SHEET_NAME
        sync: false
      - key: GOOGLE_SHEET_TAB
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
